### ISSUE TITLE
paper 1.21.1 can't use it

### ISSUE THREAD

**Issue by achenrhyc** [ChatPlugin/ChatPlugin#1]
java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.b(net.minecraft.nbt.NBTTagCompound)
[14:28:17] [Server thread/WARN]:        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2848)
[14:28:17] [Server thread/WARN]:        at pers.tany.yukinoaapi.NMSUtil.<clinit>(NMSUtil.java:102)
[14:28:17] [Server thread/WARN]:        at pers.tany.yukinoaapi.interfacepart.item.IItem.getItemNBT(IItem.java:82)
[14:28:17] [Server thread/WARN]:        at pers.tany.seekinventory.gui.OfflineInterface.onInventoryClose(OfflineInterface.java:128)
[14:28:17] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[14:28:17] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[14:28:17] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[14:28:17] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:28:17] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601)
[14:28:17] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588)
[14:28:17] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_21_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1432)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2527)
[14:28:17] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCloseWindow.a(SourceFile:32)
[14:28:17] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCloseWindow.a(SourceFile:8)
[14:28:17] [Server thread/WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:35)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.TickTask.run(SourceFile:18)
[14:28:17] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162)
[14:28:17] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203)
[14:28:17] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242)
[14:28:17] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:145)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1207)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1214)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[14:28:17] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[14:28:17] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "save" is null
[14:28:17] [Server thread/WARN]:        at pers.tany.yukinoaapi.interfacepart.item.IItem.getItemNBT(IItem.java:89)
[14:28:17] [Server thread/WARN]:        at pers.tany.seekinventory.gui.OfflineInterface.onInventoryClose(OfflineInterface.java:128)
[14:28:17] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[14:28:17] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[14:28:17] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[14:28:17] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:28:17] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601)
[14:28:17] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588)
[14:28:17] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_21_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1432)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2527)
[14:28:17] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCloseWindow.a(SourceFile:32)
[14:28:17] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCloseWindow.a(SourceFile:8)
[14:28:17] [Server thread/WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:35)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.TickTask.run(SourceFile:18)
[14:28:17] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162)
[14:28:17] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1270)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:203)
[14:28:17] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.B(SourceFile:136)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.bv(MinecraftServer.java:1249)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.B(MinecraftServer.java:1242)
[14:28:17] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:145)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1207)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1214)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1078)
[14:28:17] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[14:28:17] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Remigio07** [comment]
hey, thank you for reaching out
the log doesn't seem to contain any ChatPlugin-related issue, however 1.21.1 was not supported by v1.9.8 and errors show up if you start with that version (even though the plugin was supposed to gracefully disable when run on an unsupported version)

I have just released v1.9.9 on all platforms and it adds 1.21.1 support (f584ef8), it should fix your problems 🙂
